<template>
    <div id="all">
        <tree :list="nodes" ></tree>
    </div>
</template>
<style scoped>
    #all{
        width:100%;
        height: 100%;
    }

</style>
<script>
    export default{
        data(){
            return{
                nodes:[{
                    name:"一级节点",
                    level:0,
                    isOpen:false,
                    children:[
                        {
                            name:"页面",
                            level:1,
                            isOpen:false,
                            children:[
                                {
                                    name:"首页",
                                    level:2,
                                    url:"/home",
                                    isOpen:true,
                                    children:[]
                                },
                                {
                                    name:"节点1-2",
                                    level:2,
                                    isOpen:true,
                                    children:[]
                                }
                            ]
                        },
                        {
                            name:"ht",
                            level:1,
                            url:"/ht",
                            isOpen:false,
                            children:[
                                {
                                    name:"节点2-1",
                                    level:2,
                                    isOpen:true,
                                    children:[]
                                },
                                {
                                    name:"节点2-2",
                                    level:2,
                                    isOpen:true,
                                    children:[]
                                }
                            ]

                        }
                    ]
                },{
                    name:"一级节点2",
                    level:0,
                    isOpen:false,
                    children:[
                        {
                            name:"ht",
                            level:1,
                            url:"/ht",
                            isOpen:false,
                            children:[
                                {
                                    name:"节点2-1",
                                    level:2,
                                    isOpen:true,
                                    children:[]
                                },
                                {
                                    name:"节点2-2",
                                    level:2,
                                    isOpen:true,
                                    children:[]
                                }
                            ]

                        }
                    ]
                }]
            }
        }
    }
</script>